title: Viviana Siveroni
#logo: /assets/img/head_shot_circle.png
#description: My Portfolio
<br> </br>
<a href="https://www.linkedin.com/in/vivianasiveroni/"> Visit my LinkedIn Profile</a>
<a href="https://www.linkedin.com/in/vivianasiveroni/". or my Researchgate Profile</a>
theme: jekyll-theme-minimal
